### PR TITLE
Parallel TLB lookup

### PR DESCRIPTION
**Pull request by ngober**
This patch performs TLB lookup in parallel with the cache tag lookup, which has been requested often. It also adds full TLB lookup support for virtual-address prefetching.

The queues in the cache model are now themselves capable of generating requests to the TLBs. The TLBs have been removed from the core model. There are two kinds of cache queues: a `CACHE::TranslatingQueues` and a `CACHE::NonTranslatingQueues`, which are instantiated at configure time.

A consequence of this is that virtual-address prefetches can now be passed to the TLBs. There is now an additional configuration option: `"lower_translate"`.

    {
        "STLB" : {
            "name": "my_stlb"
        },
        "L2C" : {
            "prefetcher": "va_ampm_lite",
            "virtual_prefetch": true,
            "lower_translate": "my_stlb"
        }
    }

Most of the time, the default `lower_translate` specification should be sane, but you should pay attention to this if you are making your own designs.

This results in a pretty considerable performance increase.

### CODE REVIEW

**Comment by alberto-ros** [comment]
Does the commit misses the update to champsim_config.json?

Should it be:

 "lower_translate": "cpu0_STLB"

Or:

 "lower_translate": "STLB"

?

**Comment by ngober** [comment]
I think the example I gave wasn't great. I've edited the example configuration above. In general, the default names for TLBs and caches aren't something that the user knows or should try to name. If you want to pick a particular `lower_translate`, you should have already given the cache a name.

I added a commit that will make a core's STLB the default translation supplier for the L2C. I'm not 100% sure this is the best default. I've heard arguments that the L2C should have its own private TLB, I've heard some people say that it should go to the DTLB. In my view, if you want to make changes, those changes are available to you, but here are the defaults:

 - L1I -> ITLB
 - L1D -> DTLB
 - L2C -> STLB
 - LLC -> ??? (If you specify this, I hope you know what you're doing)

**Comment by alberto-ros** [comment]
Not I see how it works and I like it. Defaults seem okay to me. Even having a virtual prefetcher at L2C may be non-conventional.

**Comment by alberto-ros** [comment]
I found out a problem with this patch. Prefetchers do not work because of the following code at prefetch_line:

  if (fill_this_level)
    pf_packet.to_return = {this};

Prefetches should never be returned to the cache that generates them since and MSHR has not been allocated for them at the time of inserting them in the PQ.

So commenting those lines of code fixes the issue, but it neglects the fill_this_level feature.

**Comment by alberto-ros** [comment]
The other checks that I did look good :-)

**Comment by ngober** [comment]
I managed to write a test that isolated the issue and then fixed it. Thanks for bringing it to my attention.

**Comment by alberto-ros** [comment]
It seems that still there are some bugs, as I encountered a deadlock.

I just compile the code with the default options and run:

./bin/champsim -warmup_instructions 20000000 -simulation_instructions 20000000 -traces secret_int_118.champsimtrace.xz 

The trace is obtained from: https://hpca23.cse.tamu.edu/CVP-1/secret_traces/index.html

If you cannot replicate it and you want the output of the deadlock let me know it.

**Comment by ngober** [comment]
I'd be curious about this deadlock, but I'm a bit hesitant to pursue it differently since we've had some trouble with the CVP traces in the past (#112). I suspect this is a problem that would actually require us to make a new trace format to solve. I am actively working on that, and I'd be open to suggestions if you have any, but that's for another thread.

**Comment by alberto-ros** [comment]
This is a new deadlock and not related to #112, since #112 is a performance bug. I would not relate both things, as this is I guess some bug introduced in this PR (appeared in a CVP trace because I am testing them, but it could appear in another trace).

**Pull request merged**
