### PR TITLE
added predictors

### PR DESCRIPTION
**Pull request by Johngibbard**

### CODE REVIEW

**Comment by Johngibbard** [comment]
good

**Comment by ngober** [comment]
Did you intend to submit a PR to ChampSim for this? It looks like you're working on some experiments, and the patch isn't suitable to merge.

**Comment by ngober** [comment]
I'm closing this PR so that I stop getting emails about it. If you intend to prepare this for merging, let me know.

**Comment by Johngibbard** [comment]
Yeah sorry about that, Im new to github and did that by mistake

**Pull request closed without merging**
