### PR TITLE
Release Candidate 2024

### PR DESCRIPTION
**Pull request by ngober**
It is time to start considering a new release.

 - Specification for modules as objects (#330). The prior way of doing modules is now referred to as "legacy" modules and should be considered deprecated. Support for these will break when it becomes impossible to maintain. See #495 for a quick and easy example of updating your code.
 - Added a cache-fill hook to replacement policies (#434)
 - Improvements to the DRAM model and timing (#504)
 - Introduction of strong types to represent units. This change will help a lot with correctness. (#297, #367, #400)
 - More bug fixes than I think I can count

In the coming days I will continue filling out the change log. If you have changes that you think should be highlighted or if you have blocking changes that need to be resolved before this merge, comment below.

### CODE REVIEW

**Comment by dpuckett98** [comment]
@ngober #483 is closer to being ready than it was last time we talked about it, but it's definitely not ready to be merged in yet.

**Comment by maccoymerrell** [comment]
@ngober #514 This should probably be resolved before merge.

**Comment by GinoAC** [comment]
@ngober I actually have something for #350 to push with the barrier being writing quite a lot of tests. #360 builds on top of this and can definitely wait until the next release. 

Do we have a target date for the release?

**Comment by ngober** [comment]
No target date yet, I want to triage the features and issues so that we can put a timeline on it.

**Comment by ngober** [comment]
The triage list is down to 3 items, 2 of which have PRs coming down the pipe. Could someone please investigate #313 to see if it is still relevant? If not, let's close the issue and get ready to ship a new release!

**Comment by ngober** [comment]
OK, I'm going to start closing the window on this. #540 and #545 will be the last merges into develop before we create a release candidate. After that, I'll make an announcement and I would like anyone's help in stress testing the candidate, and it will probably be live by December 1st. Thank you to everyone who supported the sprint to get the next release together!

**Comment by ngober** [comment]
Also, if you would like a feature highlighted in the release notes, let me know. Currently, it is as it sits at the top of the thread. Let's stick to features, not bugfixes, since those are too numerous to count.

**Comment by ngober** [comment]
The CI for the develop branch was canceled because the tests are too slow. Something has happened in the last month to make it this way. I'm considering it a blocking issue. We cannot merge to master while the tests are taking greater than 6 hours to complete. If you have commits on develop, take a good hard look at them and try to figure out why things are slowing to a crawl.

**Comment by maccoymerrell** [comment]
@ngober It seems like the checks started getting long after #530 was merged, going from about 7-8 minutes to over an hour.

Then, it spikes again after #540 (at least this is the first tested pr that shows longer times, over 6 hours). Doesn't seem to be much of a connection there. #540 was taking about an hour before it was merged, and took 6 once it was on develop.

**Comment by ngober** [comment]
It's not compilation that is taking a long time, it's runtime. I can't say with confidence that it's our fault, but I don't see anything on my end that indicates problems with GitHub-hosted runners.

**Comment by maccoymerrell** [comment]
250-load-scheduling test never finishes. It stalls indefinitely.

**Pull request merged**
