### PR TITLE
Prevented repeated fetches to the same blocks.

### LINKED ISSUE #108: Fetcher issues (develop branch)
I changed source code a little, then I compiled by default configuration and ran ChampSim with the following command: `bin/champsim -warmup_instructions 0 -simulation_instructions 2500 -traces client_001.champsimtrace.xz`
Then I found some fetcher issues.

```diff
--- a/inc/champsim.h
+++ b/inc/champsim.h
@@ -6,7 +6,7 @@
 #include "champsim_constants.h"

 // USEFUL MACROS
-//#define DEBUG_PRINT
+#define DEBUG_PRINT
 #define SANITY_CHECK
 #define LLC_BYPASS
 #define DRC_BYPASS

--- a/src/ooo_cpu.cc
+++ b/src/ooo_cpu.cc
@@ -298,7 +298,7 @@ uint32_t O3_CPU::check_rob(uint64_t instr_id)

     for (uint32_t i=ROB.head, count=0; count<ROB.occupancy; i=(i+1==ROB.SIZE) ? 0 : i+1, count++) {
         if (ROB.entry[i].instr_id == instr_id) {
-            DP ( if (warmup_complete[ROB.cpu]) {
+            DP ( if (warmup_complete[cpu]) {
             cout << "[ROB] " << __func__ << " same instr_id: " << ROB.entry[i].instr_id;
             cout << " rob_index: " << i << endl; });
             return i;
@@ -401,7 +401,7 @@ void O3_CPU::fetch_instruction()
          else
               trace_packet.address = ifb_entry.ip >> LOG2_PAGE_SIZE;
           trace_packet.full_addr = ifb_entry.ip;
-         trace_packet.instr_id = 0;
+         trace_packet.instr_id = ifb_entry.instr_id;
          trace_packet.rob_index = i;
           trace_packet.ip = ifb_entry.ip;
          trace_packet.type = LOAD;
@@ -450,7 +450,7 @@ void O3_CPU::fetch_instruction()
           fetch_packet.full_addr = ifb_entry.instruction_pa;
           fetch_packet.v_address = ifb_entry.ip >> LOG2_PAGE_SIZE;
           fetch_packet.full_v_addr = ifb_entry.ip;
-         fetch_packet.instr_id = 0;
+         fetch_packet.instr_id = ifb_entry.instr_id;
          fetch_packet.rob_index = 0;
           fetch_packet.ip = ifb_entry.ip;
          fetch_packet.type = LOAD;
```

### ITLB is accessed multiple times but is not needed.

```
[ITLB_RQ] add_rq instr_id: 2385 address: ffffa844d full_addr: ffffa844dacc type: 0 head: 9 tail: 10 occupancy: 1 event: 24176 current: 24175
[ITLB_RQ] add_rq instr_id: 2391 address: ffffa844d full_addr: ffffa844dae4 type: 0 head: 10 tail: 11 occupancy: 1 event: 24177 current: 24176
[ITLB_RQ] add_rq instr_id: 2391 address: ffffa844d full_addr: ffffa844dae4 type: 0 head: 11 tail: 12 occupancy: 1 event: 24178 current: 24177
[ITLB_RQ] add_rq instr_id: 2397 address: ffffa844d full_addr: ffffa844dafc type: 0 head: 12 tail: 13 occupancy: 1 event: 24179 current: 24178
```

In cycle 24175, an ITLB request is issued by instr2385.
In cycle 24176, another ITLB request is issued by instr2391.
In cycle 24177, the first ITLB request is returned, and the following code restores `instr2391.translated == INFLIGHT` to `instr2391.translated == 0`, then instr2391 issues yet another ITLB request since `instr2391.translated == 0`.
In cycle 24178, the second ITLB request is returned, and it sets `instr2391.translated == COMPLETED`.
In cycle 24179, the third ITLB request is returned, but no one uses it.

https://github.com/ChampSim/ChampSim/blob/37fc62280c0752dd7c8c6f9a981c1833cf4fd4bb/src/ooo_cpu.cc#L1698-L1699

The root of this problem is that the following codes assume "all instructions on the same line can be translated in one cycle" while the above code assumes "only 6 instructions can be translated in one cycle".

https://github.com/ChampSim/ChampSim/blob/37fc62280c0752dd7c8c6f9a981c1833cf4fd4bb/src/ooo_cpu.cc#L417-L437

### Instruction fetch is done out of order. 

```
[L1I_RQ] add_rq instr_id: 2391 address: 2f0b6b full_addr: bc2dae4 type: 0 head: 3 tail: 4 occupancy: 1 event: 24182 current: 24178
[L1I_RQ] add_rq instr_id: 2398 address: 2f0b6c full_addr: bc2db00 type: 0 head: 3 tail: 5 occupancy: 2 event: 24183 current: 24179
[L1I_RQ] add_rq instr_id: 2408 address: 2f0b6f full_addr: bc2dbe4 type: 0 head: 3 tail: 6 occupancy: 3 event: 24184 current: 24180
[L1I_RQ] add_rq instr_id: 2415 address: 2f0b70 full_addr: bc2dc00 type: 0 head: 4 tail: 7 occupancy: 3 event: 24186 current: 24182
[L1I_RQ] add_rq instr_id: 2389 address: 2f0b6b full_addr: bc2dadc type: 0 head: 5 tail: 8 occupancy: 3 event: 24187 current: 24183
[L1I_RQ] add_rq instr_id: 2404 address: 2f0b6c full_addr: bc2db18 type: 0 head: 6 tail: 9 occupancy: 3 event: 24188 current: 24184
[L1I_RQ] add_rq instr_id: 2431 address: 2f0b71 full_addr: bc2dc40 type: 0 head: 6 tail: 10 occupancy: 4 event: 24188 current: 24184
[L1I_RQ] add_rq instr_id: 2414 address: 2f0b6f full_addr: bc2dbfc type: 0 head: 6 tail: 11 occupancy: 5 event: 24189 current: 24185
[L1I_RQ] add_rq instr_id: 2438 address: 19e74ee full_addr: 679d3b90 type: 0 head: 7 tail: 12 occupancy: 5 event: 24190 current: 24186
[L1I_RQ] add_rq instr_id: 2421 address: 2f0b70 full_addr: bc2dc18 type: 0 head: 8 tail: 13 occupancy: 5 event: 24191 current: 24187
[L1I_RQ] add_rq instr_id: 2450 address: 19e74ef full_addr: 679d3bc0 type: 0 head: 10 tail: 14 occupancy: 4 event: 24192 current: 24188
[L1I_RQ] add_rq instr_id: 2437 address: 2f0b71 full_addr: bc2dc58 type: 0 head: 11 tail: 15 occupancy: 4 event: 24193 current: 24189
[L1I_RQ] add_rq instr_id: 2466 address: 19e74f0 full_addr: 679d3c00 type: 0 head: 12 tail: 16 occupancy: 4 event: 24194 current: 24190
[L1I_RQ] add_rq instr_id: 2444 address: 19e74ee full_addr: 679d3ba8 type: 0 head: 13 tail: 17 occupancy: 4 event: 24195 current: 24191
[L1I_RQ] add_rq instr_id: 2427 address: 2f0b70 full_addr: bc2dc30 type: 0 head: 14 tail: 18 occupancy: 4 event: 24196 current: 24192
```

The same thing is happening.
https://github.com/ChampSim/ChampSim/blob/37fc62280c0752dd7c8c6f9a981c1833cf4fd4bb/src/ooo_cpu.cc#L1744-L1745

### PR DESCRIPTION
**Pull request by ngober**
Resolves #108.

This patch tightens the restrictions on how fetch (and fetch translate) requests may be fulfilled. The L1I and ITLB can now issue requests that satisfy larger numbers of instructions, up to the fetch buffer's capacity, but those requests must be contiguous in program order. I do not allow a block of instructions to issue a request if the tail of the block hits the end of the fetch buffer, since there may be instructions still to come within the block (see discussion in #108). The only exception to this is when the entire fetch buffer falls in the same window, which is often the case for translations.

When a block is returned, the instructions are marked and advanced in program order. Packets can be merged as they move through the cache hierarchy, and the return mechanism will mark them, since they come from the same block. There is a case where, since the decoded instruction buffer can mark instructions as translated and fetched, an instruction might have left the fetch buffer by the time its fetch is returned. In this case, the return mechanism simply ignores it and moves on. We may wish to address this in a future pass by only permitting a single check to the DIB per instruction.

I made the decision to eliminate the re-request mechanism. Once the block is in the core, it doesn't make sense to throw it away simply because we did not have enough bandwidth to mark all instructions. Since packets now remember which instructions they fulfill, the return mechanism will wait until the next cycle to continue marking instructions.

Patch #115 is a prerequisite of this patch. That patch adds the `circular_buffer` class, whose iterators are used here. Iterators to the previously-used `CORE_BUFFER` class are not ordered and would have been impossible to merge.

### CODE REVIEW

**Comment by sethpugsley** [comment]
Just so I'm clear, this includes all the performance benefit from #115, right?  When I compare the two, this seems to have slightly lower performance than #115.  Does that sound right to you?

**Comment by ngober** [comment]
This will certainly have some performance differences from #115, since we are changing the sequence in which translations and fetches are issued. I would expect the performance to be slightly negative, since the penalty of enforcing contiguous fetches probably exceeds the benefit of not re-issuing fetches.

**Comment by sethpugsley** [comment]
It's hard for me to review this code, because it includes all the changes included in #115.  When I look at the "files changed" tab, I mostly see the delay_queue changes, and I don't know immediately what novel stuff I should be evaluating.  Should we merge #115 into develop first, so that I can have a clearer picture of what's going on here?

**Comment by ngober** [comment]
This should not be merged before #115. If we decide to do other things with that PR or go a different direction with the delays, I can keep this branch up to date easily.

**Comment by ngober** [comment]
Also, you should be able to just look at the last commit. This patch is ultimately only one commit long, if #115 is taken into account.

**Comment by sethpugsley** [comment]
I think this looks good.  Based on your description, I was afraid you weren't respecting the fetch bandwidth limitations, but in the code it looks like you are.  Also, it looks like this improves simulation performance by about 15% on one trace I tested.  I'll merge this tomorrow unless someone raises an objection in the meantime.

**Pull request merged**
