### PR TITLE
Fix MacOS Compile Error

### PR DESCRIPTION
**Pull request by maccoymerrell**

### CODE REVIEW

**Comment by ngober** [comment]
Looks like this didn't fix the issue. It still interprets `*.d` as a directory.

**Comment by maccoymerrell** [comment]
I am going to try to make the other change a while back that I made to fix this on my branch.
Moved the directory rules below the .d rules.

**Comment by maccoymerrell** [comment]
Bada bing

**Comment by ngober** [comment]
I have no explanation for why this works.

**Pull request merged**
