### PR TITLE
Added delay queue to simplify timing specifications

### PR DESCRIPTION
**Pull request by ngober**
This patch introduces two classes: `champsim::delay_queue`, a sequential container in which items must sit for a fixed time before being marked ready, and `champsim::circular_buffer`, which supports it as the underlying structure.

The delay queue is a natural replacement for the decode and dispatch buffers, as well as the channels of the caches, since these queues only exist to order elements and hold them for a fixed time.

While I was in there, I converted some structures in the core model to use the new circular buffer class, since they fit. The next most obvious place to use this would be the ROB, but changing that would be extensive and probably is worth its own PR. Furthermore, this patch does not completely replace `CORE_BUFFER` and `PACKET_QUEUE`. `CORE_BUFFER` is still used for the ROB, LQ, and SQ. `PACKET_QUEUE` is still used in the DRAM model, because some elements are handled non-sequentially (See #97). Again, this is probably worth its own PR.

These changes are not performance-neutral. I think this comes from the timing at which elements are aged towards becoming ready. If there's serious concern about this, I'll look deeper into the details.

### CODE REVIEW

**Comment by sethpugsley** [comment]
I like all of this.  I think there is value in figuring out exactly why performance is so much higher with this PR than in develop, but I think this PR puts us in a much better position to be confident that all buffers throughout the system are handled in the same way.  There's are fewer places that need to be debugged in this PR than in develop.

**Comment by ngober** [comment]
Are there other places you think I should put a `circular_buffer` or a `delay_queue`?

**Comment by sethpugsley** [comment]
I think this should be merged as soon as the conflicts I just created by merging another PR into develop are resolved.

**Comment by ngober** [comment]
Ready for merge.

**Pull request merged**
